# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Build

# Setup
title:            'the relaxist'
tagline:          'a voyage'
description:      'The personal website of yours truly. An insight into my works and my thoughts. Made by <a href="https://fb.com/tusht" target="_blank">tushar</a>.'
url:              http://www.therelaxist.com
baseurl:          /

author:
  name:           'Tushar'
  url:            https://fb.com/tusht

paginate:         5

# Custom vars
version:          2.1.0

github:
  root:           https://github.com/tushart91
  repo:           https://github.com/tushart91/study-usc
