# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Build

# Setup
title:            'the relaxist'
tagline:          'a voyage'
description:      'a lazy programmer &lt;geek&gt;ing life out in LA. An insight into my thoughts and works.'
url:              http://www.therelaxist.com
baseurl:          /

author:
  name:           'Tushar'
  url:            https://fb.com/tusht

paginate:         5

# Custom vars
version:          2.1.0

github:
  root:           https://github.com/tushart91
  repo:           https://github.com/tushart91/study-usc
